services:
  - type: web
    name: fitai-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: fitai-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/build
    plan: free
